### PR TITLE
Fixes UglifyJS error about using functions inside if statements with strict mode

### PR DESCRIPTION
**Pull request by silviorelli**

### CODE REVIEW

**Comment by lndl** [comment]
Sounds good. Merged!
Thanks!

**Comment by silviorelli** [comment]
@lndl maybe it's worth releasing a new version or tag of the gem, given it caused issues with Rails 5 in production env.

**Comment by lndl** [comment]
@silviorelli, done! New version/tag now is 0.7.5

**Comment by silviorelli** [comment]
Thanks, ciao!

**Pull request merged**
